2018-04-22 00:08:13,252 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 00:43:37,085 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
2018-04-22 00:48:47,787 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
2018-04-22 00:53:57,967 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
2018-04-22 01:01:07,783 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 01:21:26,347 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 01:37:22,754 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 01:52:09,764 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 02:06:09,818 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 02:11:10,488 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 02:21:25,792 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 02:37:21,782 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 02:57:04,756 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 03:02:07,815 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 03:18:33,770 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 03:31:07,795 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 03:41:07,773 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 03:57:33,744 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 04:09:07,843 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 04:25:33,758 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 04:31:06,823 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 04:41:05,771 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 04:51:05,818 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 05:07:02,775 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 05:27:31,845 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 05:43:27,765 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 05:51:05,768 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 06:01:04,864 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 06:12:14,816 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 06:27:03,800 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 06:43:30,857 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 06:59:03,854 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 07:11:03,807 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 07:21:03,823 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 07:32:33,861 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 07:48:59,772 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 08:07:59,873 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 08:25:59,871 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 08:40:59,867 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 08:50:59,870 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 14:31:07,408 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 14:47:28,407 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 14:59:08,409 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 15:11:08,433 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 15:21:09,417 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 15:35:28,416 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 15:41:08,417 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 15:57:59,412 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
2018-04-22 16:11:08,424 16544-123145335377920 ERROR: Failed when updating the prices [in /Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py:50]
Traceback (most recent call last):
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/jobs.py", line 48, in update_prices
    global_price_new(app)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/views/public.py", line 51, in global_price_new
    cursor = okcoinSpot.kline(code, '12hour')
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/OkcoinSpotAPI.py", line 24, in kline
    return httpGet(self.__url, KLINE_RESOURCE, params)
  File "/Users/jqhuang/Desktop/python-workspace/demo/app/okexapi/HttpMD5Util.py", line 24, in httpGet
    conn.request("GET", resource + '?' + params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known
